name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-15
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - run: xcodebuild -jobs 1 -target Package -configuration Debug
      - run: xcodebuild -jobs 1 -target Package -configuration Release

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/*/*/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  analyze-clang:
    name: Analyze Clang
    runs-on: macos-15
    env:
      JOB_TYPE: ANALYZE

    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - name: Analyze Debug
        run: |
          xcodebuild analyze -quiet \
            -scheme Package \
            -target Package \
            -configuration Debug \
            CLANG_ANALYZER_OUTPUT=plist-html \
            CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze-debug"

      - name: Upload Debug analyzer reports
        # i f: always()
        uses: actions/upload-artifact@v7
        with:
          name: clang-analyze-debug
          path: clang-analyze-debug

      - name: Fail if Debug analyzer found issues
        run: |
          [ "$(find clang-analyze-debug -name "*.html" 2>/dev/null)" = "" ]

      - name: Clean
        run: xcodebuild clean -quiet -scheme Package

      - name: Analyze Release
        run: |
          xcodebuild analyze -quiet \
            -scheme Package \
            -target Package \
            -configuration Release \
            CLANG_ANALYZER_OUTPUT=plist-html \
            CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze-release"

      - name: Upload Release analyzer reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: clang-analyze-release
          path: clang-analyze-release

      - name: Fail if Release analyzer found issues
        run: |
          [ "$(find clang-analyze-release -name "*.html" 2>/dev/null)" = "" ]
